### ISSUE TITLE
Fix `audit-central-logging.md`

### ISSUE THREAD

**Issue by Freshrojek** [hmrc/platsec-aws-scanner#132]
Hi PlatSec gang!
Just noticed that in the `/docs/audit-central-logging.md` file, it states to run the command `audit_centrail_logging`instead of `audit_central_logging`.
(being a bit picky I know)

**Comment by Masquerainsley** [comment]
Jack!! lovely to hear from you, we've fixed this, thanks for bringing it to our attention :).
