### ISSUE TITLE
Some test for tests test_aws_scanner_argument_parser.py is not working correctly

### ISSUE THREAD

**Issue by martinusnel** [hmrc/platsec-aws-scanner#64]
Looking at the four tests (https://github.com/hmrc/platsec-aws-scanner/blob/main/tests/test_aws_scanner_argument_parser.py#L258 to https://github.com/hmrc/platsec-aws-scanner/blob/main/tests/test_aws_scanner_argument_parser.py#L275), I believe they are not working as expected. But who knows, I might be an idiot :)

I believe the issues are:
1. The asserts will never fire. You can set `assert False` and the unit test will pass. This is due to the assert being too far indented. It can't execute after the system exit.
2. You are checking `caplog` which only contains data from logging. The error will be on STDERR, which is captured via `capsys`, specifically `capsys.readouterr()`.

**Comment by achatain** [comment]
Good spot! Merci @martinusnel here's a PR for you :smile:

**Comment by achatain** [comment]
Fixed in #69 Merci :smile:
